name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade build twine
    - name: Create packages
      run: python -m build
    - name: Run twine check
      run: twine check dist/*
    - uses: actions/upload-artifact@v3
      with:
        name: aws-tool-dist
        path: dist
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*"
        bodyFile:  "CHANGELOG.md"
        token:     ${{ secrets.GITHUB_TOKEN }}
    - name: Upload pypi
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: twine upload --verbose dist/*
